package com.example.productsearch.repository;

import com.example.productsearch.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface ProductRepository extends JpaRepository<Product, Long> {

    // 🔹 Derived Query Methods (Auto-generated by Spring)

    // Find products by category (case-insensitive)
    List<Product> findByCategoryIgnoreCase(String category);

    // Find products within price range
    List<Product> findByPriceBetween(double min, double max);

    // Find products above a price (Derived method version)
    List<Product> findByPriceGreaterThan(double price);


    // 🔹 JPQL Query (For Demonstration Purpose Only)

    // Fetch all products sorted by price (JPQL example)
    @Query("SELECT p FROM Product p ORDER BY p.price ASC")
    List<Product> findAllSortedByPriceJPQL();

}